# Google credentials and configuration
google_client_id:      YOUR_CLIENT_ID
google_client_secret:  YOUR_CLIENT_SECRET
google_project_id:     msfit-177522

# options are "mysql", "postgres", "mongodb", or "datastore"
db_backend: mysql

# configure CloudSQL for MySQL or PostgreSQL backend
cloudsql_connection_name: msfit-177522:us-central1:ms-fit 
cloudsql_database_name: members
cloudsql_user: nicholas 
cloudsql_password: YJgdAUQ9E2eDjfMk
cloudsql_port: 3306

# configure Mongo backend
mongo_url: YOUR_MONGODB_URL
mongo_database: YOUR_MONGO_DATABASE
mongo_collection: YOUR_MONGO_COLLECTION
